const data = {
	products: [
		{
			name: "Jihyo Feel Special",
			slug: "jihyo-feel-special",
			category: "Unnie",
			image: "/images/jihyo.jpg", // 679px x 829px
			price: 120,
			countInStock: 10,
			brand: "JYP",
			rating: 4.5,
			numReviews: 10,
			description: "high quality shirt",
		},
		{
			name: "Mina Feel Special",
			slug: "mina-feel-special",
			category: "Unnie",
			image: "/images/mina.jpg",
			price: 250,
			countInStock: 20,
			brand: "JYP",
			rating: 4.0,
			numReviews: 10,
			description: "high quality product",
		},
		{
			name: "Chaeyoung Feel Special",
			slug: "chaeyoung-feel-special",
			category: "Maknae",
			image: "/images/chaeyoung.jpg",
			price: 25,
			countInStock: 15,
			brand: "JYP",
			rating: 4.5,
			numReviews: 14,
			description: "high quality product",
		},
		{
			name: "Tzuyu Feel Special",
			slug: "tzuyu-feel-special",
			category: "Maknae",
			image: "/images/tzuyu.jpg",
			price: 65,
			countInStock: 5,
			brand: "JYP",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			name: "Sana Formula of Love POB",
			slug: "sana-fol-pob",
			category: "Unnie",
			image: "/images/sana.jpg",
			price: 35,
			countInStock: 5,
			brand: "JYP",
			rating: 5.0,
			numReviews: 10,
			description: "high quality product",
		},
		{
			name: "Nayeon Taste of Love Monograph",
			slug: "nayeon-tol-mono",
			category: "Unnie",
			image: "/images/nayeon.jpg",
			price: 35,
			countInStock: 5,
			brand: "JYP",
			rating: 5.0,
			numReviews: 10,
			description:
				" TWICE MONOGRAPH Taste of Love Photocard 9ea. Nayeon Photocard Only",
		},
	],
};
export default data;
